# lang.py
LANGUAGES = {
    'ru': {
        'main_menu': '📘 Главное меню:',
        'search_keyword': '1. 🔍 Поиск по ключевому слову',
        'search_genre_year': '2. 🎞️ Поиск по жанру и диапазону годов',
        'history': '3. 📚 История запросов',
        'language': '4. 🔤 Сменить язык',
        'exit': '0. 🛑 Выход',
        'choose': 'Выберите опцию: ',
        'lang_changed': '✅ Язык изменён на русский.',
        'enter_keyword': '🔑 Введите ключевое слово: ',
        'page_nav': '➡️ Введите "n" — следующая, "p" — предыдущая, "q" — выход: ',
        'genre_title': '🎬 Доступные жанры:',
        'enter_genre': 'Введите номер или название жанра: ',
        'enter_year_from': 'Год от: ',
        'enter_year_to': 'Год до: ',
        'invalid_input': '❌ Неверный ввод.',
        'no_results': '⚠️ Ничего не найдено.',
        'exit_msg': '👋 Выход...',
    },
    'en': {
        'main_menu': '📘 Main Menu:',
        'search_keyword': '1. 🔍 Search by keyword',
        'search_genre_year': '2. 🎞️ Search by genre and year range',
        'history': '3. 📚 Search history',
        'language': '4. 🔤 Change language',
        'exit': '0. 🛑 Exit',
        'choose': 'Choose an option: ',
        'lang_changed': '✅ Language changed to English.',
        'enter_keyword': '🔑 Enter keyword: ',
        'page_nav': '➡️ Type "n" — next, "p" — previous, "q" — exit: ',
        'genre_title': '🎬 Available genres:',
        'enter_genre': 'Enter genre number or name: ',
        'enter_year_from': 'Year from: ',
        'enter_year_to': 'Year to: ',
        'invalid_input': '❌ Invalid input.',
        'no_results': '⚠️ No results found.',
        'exit_msg': '👋 Exiting...',
    }
}